### ISSUE TITLE
Empty audio causes failure

### ISSUE THREAD

**Issue by tamis-laan** [SYSTRAN/faster-whisper#1060]
I have an empty recording where the VAD completely removes all the audio. This results in a failure:
```
INFO:root:Transcribe record with id bb01e7bb-fdbf-41ae-a83a-b9b69c941f09
INFO:faster_whisper:Processing audio with duration 00:06.640
INFO:faster_whisper:VAD filter removed 00:06.640 of audio
--- Logging error ---
Traceback (most recent call last):
  File "/app/src/main.py", line 105, in main
    transcript = await asyncio.to_thread(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/transcriber.py", line 50, in transcribe_opus_ogg
    segments, info = get_model().transcribe(ogg_bytes, vad_filter=True, word_timestamps=word_timestamps)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/faster_whisper/transcribe.py", line 419, in transcribe
    language = max(
               ^^^^
ValueError: max() iterable argument is empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/app/src/main.py", line 138, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1987, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/app/src/main.py", line 115, in main
    logging.info(
Message: 'Failed to transcribe bb01e7bb-fdbf-41ae-a83a-b9b69c941f09'
Arguments: (ValueError('max() iterable argument is empty'),)
```

**Comment by MahmoudAshraf97** [comment]
Should be solved now

**Comment by vycius** [comment]
This issue still occurs when a file lacks detectable speech or VAD filters out all audio content. In these cases, a `ValueError('max() arg is an empty sequence')` is triggered.

To resolve this without breaking existing functionality, I would consider defaulting to a generic language (e.g., English) with a `language_probability` of 0 for speechless files. This approach avoids errors while clearly indicating the absence of speech.

Files that consistently reproduce this issue typically contain non-speech sounds like beeps or tones (e.g., [sample beep sound](https://pixabay.com/sound-effects/search/bleep/)).

**Comment by MahmoudAshraf97** [comment]
@vycius I still couldn't reproduce the issue on `master` branch with multiple files from the link you provided, even when transcribing a file with 0 duration with or without VAD it still returns an empty list

**Comment by vycius** [comment]
Sorry. This issue only affects version 1.0.3 and is already fixed in the master branch. It would be great to see a new release with the fix included!

**Comment by MahmoudAshraf97** [comment]
It'll be released within the next two weeks hopefully, closing this for now thanks
